### ISSUE TITLE
Add a screenshot showing what the prompt looks like

### ISSUE THREAD

**Issue by rswgnu** [olemb/git-prompt#2]
So people get an idea prior to installing and using it.

**Comment by olemb** [comment]
Sorry about this. There used to be a readme file showing the output format but I didn't get around to adding it back after I switched from Go to Bash.

I've now written new implementations in Go and Python as well as included and updated version of the old readme file. I hope this helps!

Thanks for your suggestion of a screenshot! I've been wanting to add one but I haven't yet decided what commands to use in the example. Suggestions are welcome. I'll keep this issue open until I've added an actual screenshot.

**Comment by olemb** [comment]
I've added a screenshot. Thanks for the suggestion!

**Comment by rswgnu** [comment]
Thanks, that makes the utility much clearer.
